### ISSUE TITLE
changes on RowErg

### ISSUE THREAD

**Issue by sspeed22** [apkelly/ErgEmporium#1]
Hi, don't know if this is where you want these issues.  I received the kit today, awesome little invention.  Looks like there were some changes to the RowErg.

1) Cable now runs in the arm.  Just need to take a screw out to get that apart.

2) The two screws for the PM5 mount are now very short and the nut is flanged so they don't fit into the holes.  I dremeled them out (hope I didn't wreck it), but didn't matter because the screws are too short anyway.  Will go look for some longer screws.

**Comment by apkelly** [comment]
Hey, thanks for your feedback, you can reach me here or on Etsy is you purchased a kit from there.

I'm going to look into supplying the correct length of screw and nut in the package to avoid the situation you describe, I've had several customers raise the same problem as you've experienced.

Thanks.

**Comment by svego** [comment]
Is it known what length of screws i should get?
